# Generated by Django 3.1.2 on 2020-12-19 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_products_category'),
        ('login', '0003_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='orders',
            new_name='order',
        ),
    ]
