# Generated by Django 3.1.2 on 2020-12-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20201219_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='unknown', max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
